version: "3"

services:
    nuxt:
        build: ./app/
        container_name: hello-nuxt-app
        restart: always
        ports:
            - "3000:3000"
        command: "npm run start"

    nginx:
        image: nginx:1.13
        container_name: hello-nuxt-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - nuxt
